# Generated by Django 4.0.3 on 2022-03-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0002_city_area_active_zone_city_area_metro_coverage_and_more'),
        ('simetra_app', '0004_locationofcity'),
    ]

    operations = [
    ]
