# Generated by Django 4.0.3 on 2022-03-28 18:19

from django.db import migrations, models
import simetra_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0005_merge_20220318_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area_active_zone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='area_stops_coverage_active_zone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='length_avrg_between_stops',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_accidents_per_unit',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_people_metro_access',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_people_transport_access',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_wndd_n_dead_per_people',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_working_stops_active_zone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_wounded_per_accident',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_people_metro_access',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_people_transport_access',
        ),
        migrations.RemoveField(
            model_name='city',
            name='traffic_transport',
        ),
        migrations.AddField(
            model_name='city',
            name='area_active_city_zone',
            field=models.FloatField(default=0.0, verbose_name='Площадь активной зоны города'),
        ),
        migrations.AddField(
            model_name='city',
            name='area_stops_active_zone_coverage_1000',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами                 остановок 1000м'),
        ),
        migrations.AddField(
            model_name='city',
            name='area_stops_active_zone_coverage_500',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами                 остановок 500м'),
        ),
        migrations.AddField(
            model_name='city',
            name='area_stops_active_zone_coverage_700',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами                 остановок 700м'),
        ),
        migrations.AddField(
            model_name='city',
            name='avrg_length_between_stops',
            field=models.FloatField(default=0.0, verbose_name='Средневзвешенное расстояние между остановками'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_accidents_per_transport_unit',
            field=models.FloatField(default=0.0, verbose_name='Число ДТП в расчете на единицу подвижного состава'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_people_with_metro_access',
            field=models.IntegerField(default=0, verbose_name='Население с доступом к метрополитену'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_people_with_transport_access',
            field=models.IntegerField(default=0, verbose_name='Население с доступом к общественному                 транспорту'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_working_stops_active_city_zone',
            field=models.IntegerField(default=0, verbose_name='Количество остановочных пунктов в черте активной зоны                 города'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_wounded_n_dead_per_accident',
            field=models.FloatField(default=0.0, verbose_name='Число раненых и погибших в расчете на 1 ДТП'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_wounded_n_dead_per_people',
            field=models.FloatField(default=0.0, verbose_name='Количество раненых и погибших в расчете на млн                 пассажиров'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_apartments_in_coverage_zone',
            field=models.FloatField(default=0.0, verbose_name='Доля домов в зоне покрытия'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_apartments_in_metro_coverage_zone',
            field=models.FloatField(default=0.0, verbose_name='Доля домов в зоне покрытия метрополитеном'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_people_in_coverage_zone',
            field=models.FloatField(default=0.0, verbose_name='Доля населения в зоне покрытия'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_people_in_metro_coverage_zone',
            field=models.FloatField(default=0.0, verbose_name='Доля населения в зоне покрытия метрополитеном'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_people_with_metro_access',
            field=models.FloatField(default=0.0, verbose_name='Доля населения с доступом к метрополитену'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_people_with_transport_access',
            field=models.FloatField(default=0.0, verbose_name='Доля населения с доступом к общественному                 транспорту'),
        ),
        migrations.AddField(
            model_name='city',
            name='traffic_ground_transport',
            field=models.FloatField(default=0.0, verbose_name='Пассажиропоток наземного общественного транспорта'),
        ),
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.ImageField(default='main_page/bosses/default-avatar.jpg', upload_to=simetra_app.models.Boss.get_upload_path),
        ),
        migrations.AlterField(
            model_name='city',
            name='area_metro_coverage',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия станциями метрополитена'),
        ),
        migrations.AlterField(
            model_name='city',
            name='density_stops_active_zone',
            field=models.FloatField(default=0.0, verbose_name='Плотность остановок распределения остановочных пунктов                 по территории активной зоны города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_UDS',
            field=models.FloatField(default=0.0, verbose_name='Протяженность УДС первой/второй категории'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_accidents',
            field=models.IntegerField(default=0, verbose_name='Число ДТП с участием ОТ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_death_toll',
            field=models.IntegerField(default=0, verbose_name='Число погибших на ОТ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_of_apartments',
            field=models.IntegerField(default=0, verbose_name='Кол-во многоквартирных домов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_population',
            field=models.FloatField(default=0.0, verbose_name='Численность населения'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_working_stops_overall',
            field=models.IntegerField(default=0, verbose_name='Количество действующих остановочных пунктов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_wounded',
            field=models.IntegerField(default=0, verbose_name='Число раненых на ОТ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_metro_covered_area',
            field=models.FloatField(default=0.0, verbose_name='Процент покрытой территории от станций метрополитена'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_transport_covered_area',
            field=models.FloatField(default=0.0, verbose_name='Процент покрытой территории'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_affordability',
            field=models.FloatField(default=0.0, verbose_name='Ценовая доступность'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_comfort_n_convenience',
            field=models.FloatField(default=0.0, verbose_name='Комфорт и удобство'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_physical_availability',
            field=models.FloatField(default=0.0, verbose_name='Физическая доступность'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_route_network_efficiency',
            field=models.FloatField(default=0.0, verbose_name='Эффективность маршрутной сети'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_security_n_development',
            field=models.FloatField(default=0.0, verbose_name='Безопасность и устойчивое развитие'),
        ),
        migrations.AlterField(
            model_name='city',
            name='traffic_metro',
            field=models.FloatField(default=0.0, verbose_name='Пассажиропоток метрополитена'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='main_page/employees/default-avatar.jpg', upload_to=simetra_app.models.Employee.get_upload_path),
        ),
    ]
