# Generated by Django 4.0.3 on 2022-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0006_remove_city_area_active_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='num_big_trollebuses_registry',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_buses_registry',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_trollebuses',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_trollebuses_registry',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_very_big_trollebuses_registry',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_working_trollebuses',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_big_capacity_transport',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_elctro_transport',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_low_profile_transport',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_working_transport',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_working_trollebuses',
        ),
        migrations.AddField(
            model_name='city',
            name='num_all_buses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество всех автобусов по Реестру'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_all_trolleybuses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество всех троллейбусов и электробусов по Реестру'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_big_trolleybuses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество троллейбусов и электробусов большого класса                 по Реестру'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_trolleybuses',
            field=models.IntegerField(default=0, verbose_name='Количество троллейбусных машин'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_very_big_trolleybuses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество троллейбусов и электробусов особо большого                 класса по Реестру'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_working_trolleybuses',
            field=models.IntegerField(default=0, verbose_name='Количество исправных троллейбусных машин'),
        ),
        migrations.AddField(
            model_name='city',
            name='percent_working_trolleybuses',
            field=models.FloatField(default=0.0, verbose_name='Процент исправных троллейбусных машин'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_big_capacity_transport',
            field=models.FloatField(default=0.0, verbose_name='Доля ТС большой вместимости'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_electro_transport',
            field=models.FloatField(default=0.0, verbose_name='Доля электротранспорта в парке ТС НОТ'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_low_profile_transport',
            field=models.FloatField(default=0.0, verbose_name='Доля ТС с низкопольными площадками'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_working_transport',
            field=models.FloatField(default=0.0, verbose_name='Доля рабочего ПС в парке ТС'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avrg_age_bus',
            field=models.FloatField(default=0.0, verbose_name='Средний возраст автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avrg_age_electrobus',
            field=models.FloatField(default=0.0, verbose_name='Средний возраст электробусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avrg_age_metro_car',
            field=models.FloatField(default=0.0, verbose_name='Средний возраст вагонов метро'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avrg_age_tramway_car',
            field=models.FloatField(default=0.0, verbose_name='Средний возраст трамвайных вагонов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avrg_age_trolleybus',
            field=models.FloatField(default=0.0, verbose_name='Средний возраст троллейбусных машин'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_big_buses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество автобусов большого класса по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_big_tramway_cars_registry',
            field=models.IntegerField(default=0, verbose_name='Количество трамваев большого класаа по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_buses',
            field=models.IntegerField(default=0, verbose_name='Количество автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_electrobuses',
            field=models.IntegerField(default=0, verbose_name='Количество электробусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_low_profile_buses',
            field=models.IntegerField(default=0, verbose_name='Количество низкопольных автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_low_profile_electrobuses',
            field=models.IntegerField(default=0, verbose_name='Количество низкопольных электробусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_low_profile_tramway_cars',
            field=models.IntegerField(default=0, verbose_name='Количество низкопольных трамвайных вагонов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_low_profile_trolleybuses',
            field=models.IntegerField(default=0, verbose_name='Количество низкопольных троллейбусных машин'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_medium_buses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество автобусов среднего класса по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_metro_cars',
            field=models.IntegerField(default=0, verbose_name='Количество вагонов метрополитена'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_new_GET',
            field=models.IntegerField(default=0, verbose_name='Обновленный подвижной состав ГЭТ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_new_buses',
            field=models.IntegerField(default=0, verbose_name='Обновленный подвижной состав автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_small_buses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество автобусов малого класса по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_tramway_cars',
            field=models.IntegerField(default=0, verbose_name='Количество трамвайных вагонов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_tramway_cars_registry',
            field=models.IntegerField(default=0, verbose_name='Количество всех трамваев по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_very_big_buses_registry',
            field=models.IntegerField(default=0, verbose_name='Количество автобусов особо большого класса по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_very_big_tramway_cars_registry',
            field=models.IntegerField(default=0, verbose_name='Количество трамваев особо большого класаа по Реестру'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_working_buses',
            field=models.IntegerField(default=0, verbose_name='Количество исправных автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_working_electrobuses',
            field=models.IntegerField(default=0, verbose_name='Количество исправных электробусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_working_metro_cars',
            field=models.IntegerField(default=0, verbose_name='Количество исправных вагонов метрополитена'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_working_tramway_cars',
            field=models.IntegerField(default=0, verbose_name='Количество исправных трамвайных вагонов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_renew_program',
            field=models.FloatField(default=0.0, verbose_name='Участие в программах обновления подвижного состава –                 булев атрибут'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_working_buses',
            field=models.FloatField(default=0.0, verbose_name='Процент исправных автобусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_working_electrobuses',
            field=models.FloatField(default=0.0, verbose_name='Процент исправных электробусов'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_working_metro_cars',
            field=models.FloatField(default=0.0, verbose_name='Процент исправных вагонов метрополитена'),
        ),
        migrations.AlterField(
            model_name='city',
            name='percent_working_tramway_cars',
            field=models.FloatField(default=0.0, verbose_name='Процент исправных трамвайных вагонов'),
        ),
    ]
