# Generated by Django 4.0.3 on 2022-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0007_remove_city_num_big_trollebuses_registry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='percent_renew_program',
            field=models.FloatField(default=0.0, verbose_name='Участие в программах обновления подвижного состава'),
        ),
    ]
