# Generated by Django 4.0.3 on 2022-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0008_alter_city_percent_renew_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='bool_day_tariff',
        ),
        migrations.RemoveField(
            model_name='city',
            name='bool_long_time_tariff',
        ),
        migrations.RemoveField(
            model_name='city',
            name='bool_transfer_tariff',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cost_one_travel_ticket',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cost_transfer_ticket',
        ),
        migrations.RemoveField(
            model_name='city',
            name='income_avrg',
        ),
        migrations.RemoveField(
            model_name='city',
            name='length_overall_unrailed_path',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_in_use_bus_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_in_use_overall_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_in_use_tramway_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_in_use_trolleybus_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_regulated_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_routes_with_ticket',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_routes_with_transfer_ticket',
        ),
        migrations.RemoveField(
            model_name='city',
            name='num_unregulated_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_tramway_net_use',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_tramway_routes_isolation',
        ),
        migrations.RemoveField(
            model_name='city',
            name='percent_trolleybus_net_use',
        ),
        migrations.RemoveField(
            model_name='city',
            name='ratio_ticket_cost_income',
        ),
        migrations.RemoveField(
            model_name='city',
            name='real_time_internet_movement_information',
        ),
        migrations.RemoveField(
            model_name='city',
            name='route_coefficient',
        ),
        migrations.RemoveField(
            model_name='city',
            name='salary_avrg',
        ),
        migrations.RemoveField(
            model_name='city',
            name='share_unregulated_routes',
        ),
        migrations.RemoveField(
            model_name='city',
            name='transport_app_existance',
        ),
        migrations.RemoveField(
            model_name='city',
            name='transport_movement_schedule_website',
        ),
        migrations.RemoveField(
            model_name='city',
            name='transport_route_net_map',
        ),
        migrations.RemoveField(
            model_name='city',
            name='unique_transporte_style',
        ),
        migrations.AddField(
            model_name='city',
            name='avrg_region_income',
            field=models.IntegerField(default=0, verbose_name='Среднедушевые взвешенные доходы населения по региону'),
        ),
        migrations.AddField(
            model_name='city',
            name='avrg_region_salary',
            field=models.IntegerField(default=0, verbose_name='Средняя заработная плата по региону'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_day_pass',
            field=models.BooleanField(default=False, verbose_name='Наличие тарифа на сутки и более'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_long_period_pass',
            field=models.BooleanField(default=False, verbose_name='Наличие проездных билетов на длительный срок'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_rt_internet_movement_info',
            field=models.FloatField(default=0.0, verbose_name='Доступность информации о движении ОТ в режиме реального                 времени через Интернет'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_transfer_pass',
            field=models.BooleanField(default=False, verbose_name='Наличие пересадочного тарифа'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_transport_app',
            field=models.FloatField(default=0.0, verbose_name='Наличие официального/неофициального транспортного                 приложения'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_transport_route_net_map',
            field=models.FloatField(default=0.0, verbose_name='Наличие карт-схем маршрутной сети'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_transport_schedule_website',
            field=models.FloatField(default=0.0, verbose_name='Наличие сайта с расписаниями движениями транспорта'),
        ),
        migrations.AddField(
            model_name='city',
            name='bool_unique_transporte_style',
            field=models.FloatField(default=0.0, verbose_name='Фирменный стиль общественного транспорта'),
        ),
        migrations.AddField(
            model_name='city',
            name='coeff_non_straight_route',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент непрямолинейности маршрутов НОТ'),
        ),
        migrations.AddField(
            model_name='city',
            name='coeff_route',
            field=models.FloatField(default=0.0, verbose_name='Маршрутный коэффициент'),
        ),
        migrations.AddField(
            model_name='city',
            name='coeff_tramway_net_use',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент использования трамвайной сети'),
        ),
        migrations.AddField(
            model_name='city',
            name='coeff_trolleybus_net_use',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент использования троллейбусной сети'),
        ),
        migrations.AddField(
            model_name='city',
            name='length_overall_nonrailed_transport_path',
            field=models.FloatField(default=0.0, verbose_name='Суммарная длина выделенных полос нерельсового ОТ'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_in_use_bus',
            field=models.IntegerField(default=0, verbose_name='Количество действующих автобусных маршрутов'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_in_use_overall',
            field=models.IntegerField(default=0, verbose_name='Количество действующих маршрутов – всего'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_in_use_tramway',
            field=models.IntegerField(default=0, verbose_name='Количество действующих трамвайных маршрутов'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_in_use_trolleybus',
            field=models.IntegerField(default=0, verbose_name='Количество действующих троллейбусных маршрутов'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_regulated_tariff',
            field=models.IntegerField(default=0, verbose_name='Количество маршрутов на регулируемом тарифе'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_unregulated_tariff',
            field=models.IntegerField(default=0, verbose_name='Количество маршрутов на нерегулируемом тарифе'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_with_pass',
            field=models.IntegerField(default=0, verbose_name='Количество маршрутов, на которых доступен проездной                 билет'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_routes_with_transfer_pass',
            field=models.IntegerField(default=0, verbose_name='Количество маршрутов, на которых доступен пересадочный                 билет'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_segments_avrg_load',
            field=models.IntegerField(default=0, verbose_name='Количество сегментов, работающих в режиме средней                 загрузки'),
        ),
        migrations.AddField(
            model_name='city',
            name='num_segments_high_load',
            field=models.IntegerField(default=0, verbose_name='Количество сегментов, работающих в режиме повышенной                 загрузки'),
        ),
        migrations.AddField(
            model_name='city',
            name='percent_isolated_tramway_routes',
            field=models.FloatField(default=0.0, verbose_name='Процент обособления трамвайных путей'),
        ),
        migrations.AddField(
            model_name='city',
            name='price_SOT',
            field=models.IntegerField(default=0, verbose_name='Социально-ориентированный тариф'),
        ),
        migrations.AddField(
            model_name='city',
            name='price_monthly_transport_pass',
            field=models.IntegerField(default=0, verbose_name='Стоимость(месячного) проездного билета'),
        ),
        migrations.AddField(
            model_name='city',
            name='price_one_time_ticket',
            field=models.IntegerField(default=0, verbose_name='Стоимость разового билета на проезд'),
        ),
        migrations.AddField(
            model_name='city',
            name='price_one_time_ticket_discount',
            field=models.IntegerField(default=0, verbose_name='Стоимость проезда с учетом максимальной скидки'),
        ),
        migrations.AddField(
            model_name='city',
            name='price_transfer_pass',
            field=models.IntegerField(default=0, verbose_name='Стоимость пересадочного тарифа'),
        ),
        migrations.AddField(
            model_name='city',
            name='proportion_routes_unregulated_tariff',
            field=models.IntegerField(default=0, verbose_name='Доля маршрутов, работающих на принципах нерегулируемого                 тарифа'),
        ),
        migrations.AddField(
            model_name='city',
            name='ratio_pass_cost_to_income',
            field=models.FloatField(default=0, verbose_name='Отношение стоимость проездного билета к среднедушевым                 доходам населения'),
        ),
        migrations.AlterField(
            model_name='city',
            name='bool_nfc_payment',
            field=models.BooleanField(default=False, verbose_name='Возможность оплаты проезда внутри ТС с помощью                 мобильных устройств или банковских карт'),
        ),
        migrations.AlterField(
            model_name='city',
            name='bool_online_payment',
            field=models.BooleanField(default=False, verbose_name='Возможность дистанционного пополнения баланса'),
        ),
        migrations.AlterField(
            model_name='city',
            name='bool_universal_transport_card',
            field=models.BooleanField(default=False, verbose_name='Наличие универсальной транспортной карты'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_avrg_bus_route',
            field=models.FloatField(default=0.0, verbose_name='Средняя длина автобусного маршрута'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_avrg_tramway_route',
            field=models.FloatField(default=0.0, verbose_name='Средняя длина трамвайного маршрута'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_avrg_trolleybus_route',
            field=models.FloatField(default=0.0, verbose_name='Средняя длина троллейбусного маршрута'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_existing_tramway_routes',
            field=models.FloatField(default=0.0, verbose_name='Длина существующих трамвайных путей'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_existing_trolleybus_routes',
            field=models.FloatField(default=0.0, verbose_name='Длина существующей троллейбусной КС'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_in_use_tramway_routes',
            field=models.FloatField(default=0.0, verbose_name='Длина действующих трамвайных путей'),
        ),
        migrations.AlterField(
            model_name='city',
            name='length_in_use_trolleybus_routes',
            field=models.FloatField(default=0.0, verbose_name='Длина действующей троллейбусной КС'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_avrg_waiting_any_transport',
            field=models.FloatField(default=0.0, verbose_name='Среднее время ожидания любого маршрута на остановке'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_avrg_waiting_specific_transport',
            field=models.FloatField(default=0.0, verbose_name='Среднее время ожидания конкретного маршрута на                 остановке'),
        ),
    ]
