# Generated by Django 4.0.3 on 2022-04-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0010_alter_city_num_working_stops_active_city_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area_stops_active_zone_coverage_1000',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами остановок 1000м'),
        ),
        migrations.AlterField(
            model_name='city',
            name='area_stops_active_zone_coverage_500',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами остановок 500м'),
        ),
        migrations.AlterField(
            model_name='city',
            name='area_stops_active_zone_coverage_700',
            field=models.FloatField(default=0.0, verbose_name='Площадь покрытия активной зоны города пунктами остановок 700м'),
        ),
        migrations.AlterField(
            model_name='city',
            name='density_stops_active_zone',
            field=models.FloatField(default=0.0, verbose_name='Плотность остановок распределения остановочных пунктов по территории активной зоны города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_people_with_transport_access',
            field=models.IntegerField(default=0, verbose_name='Население с доступом к общественному транспорту'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_wounded_n_dead_per_people',
            field=models.FloatField(default=0.0, verbose_name='Количество раненых и погибших в расчете на млн пассажиров'),
        ),
        migrations.AlterField(
            model_name='city',
            name='proportion_people_with_transport_access',
            field=models.FloatField(default=0.0, verbose_name='Доля населения с доступом к общественному транспорту'),
        ),
    ]
