# Generated by Django 4.0.3 on 2022-04-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0014_alter_city_bool_nfc_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='bool_transport_schedule_website',
            field=models.FloatField(default=0.0, verbose_name='Наличие сайта с расписаниями движения транспорта'),
        ),
    ]
