# Generated by Django 4.0.3 on 2022-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0015_alter_city_bool_transport_schedule_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='bool_transport_route_net_map',
            field=models.FloatField(default=0.0, verbose_name='Наличие карт-схем маршрутной сети в сети Интернет'),
        ),
    ]
