# Generated by Django 4.0.3 on 2022-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0017_alter_city_ratio_pass_cost_to_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='russian_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
