# Generated by Django 4.0.3 on 2022-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0018_city_russian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sum_of_rating',
            field=models.FloatField(default=0.0, verbose_name='Итоговый рейтинг'),
        ),
    ]
