# Generated by Django 4.0.3 on 2022-04-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0019_city_region_alter_city_russian_name'),
        ('simetra_app', '0019_city_sum_of_rating'),
    ]

    operations = [
    ]
