# Generated by Django 4.0.3 on 2022-04-15 06:10

from django.db import migrations, models
import simetra_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('simetra_app', '0020_merge_20220411_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='avatar',
            field=models.ImageField(default='city_page/european-city.jpg', upload_to=simetra_app.models.City.get_upload_path),
        ),
    ]
